server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cs209
    username: gfzum
    password: 2333


